name: CI

on:
  push:
  pull_request:

jobs:
 Build:
  runs-on: ubuntu-latest
  env:
    CC: clang
    CXX: clang++
    npm_config_clang: 1
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: Install Node
      with:
        node-version: 20
    - name: Install module
      run: |
        npm run prepare
        npm install
    - name: Run tests
      run: |
        npm run lint
        npm run test
